### ISSUE TITLE
Elevate privilages only when needed

### ISSUE THREAD

**Issue by VoltaireNoir** [SubconsciousCompute/meta-package-manager#25]
mpm CLI attempts to elevate privileges for all commands. Commands such as help, search, list, managers, etc do not require sudo privileges. Since the password is asked for every command, this negatively affects the user experience.

## Solution
- Attempt to elevate privileges only for commands that need it

**Comment by dilawar** [comment]
This has been fixed in #27 . Using `sudo` crate. It doesn't work on Windows though.
