### ISSUE TITLE
MPM fails to compile on Windows

### ISSUE THREAD

**Issue by VoltaireNoir** [SubconsciousCompute/meta-package-manager#26]
The crate is failing to compile on Windows. This is caused by the `elevate` crate's `with_env` function. This is only available on [Unix based OSs](https://github.com/alxpettit/elevate/blob/b94f8acaea25c25b1861ff30b1e4a284e6ed86aa/src/lib.rs#L46) and should be conditionally compiled with `#[cfg(unix)]` or called with the `if_cfg` macro.

**Comment by dilawar** [comment]
Fixed it in #25
