### ISSUE TITLE
Sudo fails in CI - Unable to run tests with elevated privilage

### ISSUE THREAD

**Issue by VoltaireNoir** [SubconsciousCompute/meta-package-manager#7]
[Sudo fails](https://github.com/VoltaireNoir/genpack/actions/runs/6468304788/job/17560070608#step:5:8) while it should work as Github CI runners use passwordless sudo.
Required to make APT integration tests work (#6)

**Comment by VoltaireNoir** [comment]
@dilawar The CI is currently failing because of this. Those tests that require this were previously ignored, but we're now running them.

**Comment by dilawar** [comment]
Fixed by #25
